app1/urls.py
from django.urls import path
from app1.views import *
app_name='venkatesh'
urlpatterns=[
    path('venkatesh/',venkatesh,name='venkatesh'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='isha'
urlpatterns=[
    path('isha/',isha,name='isha'),
]

project18/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def venkatesh(request):
    return render(request,'venkatesh.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def isha(request):
    return render(request,'isha.html')

templates/isha.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>

        <h1> Om Namashivaya Namaha </h1>
        <h2> It is located in coimbatore </h2>

        <img src="{% static 'images/isha.jpg' %}" alt="" srcset=""height='500px'width='500px'>

        <a href="{% url 'venkatesh:venkatesh' %}"> click here to go venkateshwara information </a>

        <link rel="stylesheet" href="{% static 'css/c2.css' %}">

    </center>
    
    
</body>
</html>

templates/venkatesh.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>

        <h1> Om Namo Venkatesaya </h1>
        <h2> Tirumala Tirupati Devasthanams </h2>

        <img src="{% static 'images/venkateshwara.jpg' %}" alt="" srcset=""height='500px'width='500px'>

        <a href="{% url 'isha:isha' %}">click here to go isha information</a>

        <link rel ="stylesheet" href="{% static 'css/c1.css' %}">
        

        </center>
    
</body>
</html>